os:
    editCommand: 'nvr'
    editCommandTemplate: '{{editor}} --servername /tmp/`tmux display-message -p "#S-#{window_index}-#I"` -cc split -c "only" --remote +{{line}} -- {{filename}}'
promptToReturnFromSubprocess: false
git:
    commit:
        signOff: true
    merging:
        args: "--no-ff"
    pull:
        mode: "ff-only"
    log:
        showSignature: true
