"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[hostname]
ssh_only=false
format = '[$ssh_symbol](bold blue) [$hostname](bold red) '
disabled = false

[git_branch]
symbol = "🌱"

[python]
disabled = true

[cmake]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
