#!/bin/zsh

cd $(git worktree list | grep dummy | cut -f 1 -d " ")
selected_worktree=$(git worktree list | fzf | cut -f 1 -d " ")

if [[ -z $selected_worktree ]]; then
  return
fi

git worktree remove $selected_worktree
