require("aaron.telescope")
require("aaron.harpoon")
require("aaron.lsp")
require("aaron.cmp")
require("aaron.telekasten")
-- require("aaron.treesitter")
require("aaron.nvim-tree")
-- require("aaron.feline")
require("gitsigns").setup()
require("octo").setup()
