require("aaron.telescope")
require("aaron.harpoon")
require("aaron.lsp")
require("aaron.treesitter")
require("aaron.nvim-tree")
--require("aaron.feline")
require("gitsigns").setup()
require("octo").setup()
